#
# Copyright (c) 2020 Jeaustin Sirias
#
version: "3.8"
services: 
    # Django main service
    django:
        build: .
        container_name: Backend-Test-Sirias
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
            - CELERY_BROKER=pyamqp://guest@localhost//
            - CELERY_BACKEND=pyamqp://guest@localhost//
        depends_on:
            - rabbitmq
            - celery
    # The celery service
    celery:
        build: .
        command: celery worker --main=core --loglevel=info
        volumes:
            - .:/usr/src/app
        depends_on:
            #- django
            - rabbitmq
    # RabbitMQ service port
    rabbitmq:
        image: "rabbitmq:3.7-alpine"



