# Generated by Django 3.1.2 on 2020-12-01 23:09

import application.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_one', models.CharField(max_length=255)),
                ('meal_two', models.CharField(max_length=255)),
                ('meal_three', models.CharField(max_length=255)),
                ('meal_four', models.CharField(max_length=255)),
                ('date', models.DateField(blank=True, default=None, null=True, validators=[application.models.validate_date])),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3'), ('Option 4', 'Option 4')], max_length=255)),
                ('preference', models.CharField(max_length=40)),
                ('date', models.DateField(default=django.utils.timezone.localdate, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
