# Generated by Django 3.1.2 on 2020-11-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_one', models.CharField(max_length=255)),
                ('meal_two', models.CharField(max_length=255)),
                ('meal_three', models.CharField(max_length=255)),
                ('meal_four', models.CharField(max_length=255)),
            ],
        ),
    ]
