# Generated by Django 3.1.2 on 2020-12-03 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='optionFour',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='menu',
            name='optionOne',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='menu',
            name='optionThree',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='menu',
            name='optionTwo',
            field=models.CharField(max_length=40),
        ),
    ]
