# Generated by Django 3.1.2 on 2020-11-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefered_meal', models.CharField(max_length=255)),
                ('custom_preference', models.CharField(max_length=255)),
            ],
        ),
    ]
