# Generated by Django 3.1.2 on 2020-11-29 00:04

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, validators=[application.models.validate_date]),
        ),
    ]
