# Generated by Django 3.1.2 on 2020-12-02 02:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0003_auto_20201201_2047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employee',
            new_name='lunch',
        ),
    ]
