# Generated by Django 3.1.2 on 2020-11-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_menu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='prefered_meal',
            field=models.CharField(choices=[('Option 1', 'Option 1'), ('Option 2', 'Option 2'), ('Option 3', 'Option 3'), ('Option 4', 'Option 4')], max_length=255),
        ),
    ]
