# Generated by Django 3.1.2 on 2020-12-02 03:05

import application.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20201201_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, validators=[application.models.validate_date]),
            preserve_default=False,
        ),
    ]
