# Generated by Django 3.1.2 on 2020-11-30 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_employee_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.menu'),
        ),
    ]
