# Generated by Django 3.1.2 on 2020-11-30 21:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201130_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Menu',
        ),
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.localdate),
            preserve_default=False,
        ),
    ]
