# Generated by Django 3.1.2 on 2020-12-02 04:48

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_auto_20201202_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(blank=True, null=True, validators=[application.models.validate_date]),
        ),
    ]
