# Generated by Django 3.1.2 on 2020-12-02 06:08

import application.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20201202_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, validators=[application.models.validate_date]),
        ),
    ]
