# Generated by Django 3.1.2 on 2020-12-02 06:11

import application.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20201202_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='date',
            field=models.DateField(validators=[application.models.validate_date]),
        ),
    ]
