# Generated by Django 3.1.2 on 2020-11-30 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20201130_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.localdate, editable=False, max_length=11),
        ),
    ]
