# Generated by Django 3.1.2 on 2020-12-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20201202_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='preference',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
