# Generated by Django 3.1.2 on 2020-11-30 23:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20201130_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
    ]
