# Generated by Django 3.1.2 on 2020-12-02 18:25

import application.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20201202_0338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='meal_four',
            new_name='optionFour',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='meal_one',
            new_name='optionOne',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='meal_three',
            new_name='optionThree',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='meal_two',
            new_name='optionTwo',
        ),
        migrations.AddField(
            model_name='menu',
            name='uuid',
            field=models.UUIDField(default=application.utils.spawn_uuid, editable=False),
        ),
    ]
