# Generated by Django 3.1.2 on 2020-11-30 23:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20201130_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='prefered_meal',
            new_name='option',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='custom_preference',
        ),
        migrations.AddField(
            model_name='employee',
            name='preference',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
